hl.on("hyprland.start", function()
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("/home/ankit/.config/hypr/hyprlock/media-art.sh")
	hl.exec_cmd("hyprpm reload -n")
	hl.exec_cmd("wl-paste --watch cliphist store")
	hl.exec_cmd("wayle panel start ")
	hl.exec_cmd("hyprpaper --config ~/.config/hypr/hyprpaper.conf ")
	hl.exec_cmd("kdeconnectd ")
	hl.exec_cmd("kdeconnect-indicator ")
	hl.exec_cmd("hypridle ")
	hl.exec_cmd("copyq")
end)
