
wallpaper {
    monitor = HDMI-A-1
    # path = /home/ankit/Pictures/Wallpapers/aesthetic-neon-wallpaper.jpg
    path = /home/ankit/Pictures/Wallpapers/859d1t.webp
    # path = /home/ankit/Pictures/Wallpapers/Cyberpunk-Coastal.png
	fit_mode = cover
}

splash = false

