[general]
font-sans = "JetBrains Mono Nerd Font"

[bar]
scale = 0.699999988079071
location = "bottom"
inset-ends = 0.5
padding = 0.4000000059604645
padding-ends = 0.4000000059604645
module-gap = 0.4000000059604645
bg = "bg-base"
border-width = 1
rounding = "lg"
button-variant = "icon-square"
button-bg-opacity = 70
button-icon-size = 0.949999988079071
button-label-size = 1.2000000476837158
button-label-weight = "bold"
button-rounding = "lg"
button-group-background = "bg-surface"
button-group-opacity = 70

[[bar.layout]]
monitor = "*"
show = true
left = [
    "hyprland-workspaces",
    "media",
    "cava",
]
center = [
    "clock",
    "idle-inhibit",
    "notifications",
]
right = [
    "netstat",
    "cpu",
    "ram",
    { name = "audio", modules = [
    "volume",
    "microphone",
] },
    "network",
    "bluetooth",
    "systray",
    "dashboard",
]

[styling]
scale = 1.0
matugen-scheme = "content"

[styling.palette]
bg = "#0d0c0c"
surface = "#181616"
elevated = "#282727"
fg = "#c5c9c5"
fg-muted = "#a6a69c"
primary = "#8992a7"
red = "#c4746e"
yellow = "#c4b28a"
green = "#87a987"
blue = "#8ba4b0"

[modules.bluetooth]
border-color = "green"
icon-color = "bg-elevated"
icon-bg-color = "green"
label-color = "fg-default"
button-bg-color = "bg-surface"

[modules.cava]
bars = 40
color = "#deddda"
button-bg-color = "bg-surface"
bar-width = 2
border-color = "green"

[modules.clock]
format = "%d/%m/%y — %H:%M"
border-color = "yellow"
icon-color = "accent"
icon-show = false
label-color = "fg-default"
button-bg-color = "bg-surface"

[modules.cpu]
border-color = "fg-muted"
icon-color = "bg-elevated"
icon-bg-color = "green"
label-color = "fg-default"
button-bg-color = "bg-surface"

[modules.dashboard]
icon-color = "fg-default"
icon-bg-color = "bg-elevated"
right-click = "exec kitty"

[modules.hyprland-workspaces]
min-workspace-count = 0
show-special = false 
divider = "|"
app-icons-show = true
workspace-padding = 0.5
label-size = 0.8999999761581421
occupied-color = "fg-default"
container-bg-color = "bg-surface"
border-color = "green"

[modules.idle-inhibit]
border-color = "yellow"
label-show = false
icon-color = "fg-default"
icon-bg-color = "bg-surface"

[modules.media]
border-color = "green"
icon-color = "green"
icon-bg-color = "transparent"
label-color = "fg-default"
button-bg-color = "bg-surface"

[modules.media.player-icons]

[modules.microphone]
icon-color = "bg-elevated"
icon-bg-color = "green"
label-color = "fg-default"
button-bg-color = "transparent"
scroll-up = "wayle audio input-volume +5"
scroll-down = "wayle audio input-volume -5"

[modules.network]
border-color = "fg-default"
icon-color = "bg-elevated"
icon-bg-color = "green"
label-color = "fg-default"
button-bg-color = "bg-surface"

[modules.netstat]
label-color = "fg-default"
format = " {{ down_auto }}   {{ up_auto }}"
icon-show = false
button-bg-color = "bg-surface"

[modules.notifications]
label-show = false
border-color = "yellow"
icon-color = "fg-default"
icon-bg-color = "transparent"
label-color = "fg-default"
button-bg-color = "bg-surface"
popup-close-behavior = "remove"
popup-urgency-bar = "none"

[modules.ram]
icon-color = "bg-elevated"
label-color = "fg-default"
button-bg-color = "bg-surface"

[modules.separator]
color = "fg-default"

[modules.systray]
icon-scale = 1.100000023841858
border-color = "yellow"
button-bg-color = "bg-surface"

[modules.volume]
icon-color = "bg-elevated"
icon-bg-color = "green"
label-color = "fg-default"
button-bg-color = "transparent"

[modules.weather]
location = "Kolkata"

[wallpaper]
engine-enabled = false
