[general]
font-sans = "JetBrains Mono Nerd Font"

[bar]
rounding = "md"
button-bg-opacity = 70
button-icon-size = 0.75
button-label-size = 1.0
button-label-weight = "bold"
button-group-background = "bg-surface"
button-group-opacity = 70

[styling]
scale = 1.0

[styling.palette]
bg = "#11111b"
surface = "#13262e"
elevated = "#13262e"
fg-muted = "#babbf1"
primary = "#babbf1"
red = "#e01b24"
yellow = "#f6d32d"
green = "#33d17a"
blue = "#1c71d8"

[modules.bluetooth]
icon-color = "status-info"
icon-bg-color = "bg-surface"
label-color = "accent"
button-bg-color = "bg-surface"

[modules.cava]
bars = 40
color = "#babbf1"
button-bg-color = "bg-surface"
bar-width = 2

[modules.clock]
format = "%d/%m/%y — %H:%M"
icon-color = "accent"
button-bg-color = "bg-surface"

[modules.dashboard]
border-color = "accent"
icon-bg-color = "fg-muted"
right-click = "exec kitty"

[modules.hyprland-workspaces]
icon-size = 0.75
label-size = 0.75
active-indicator = "underline"
active-color = "fg-default"
occupied-color = "fg-default"
container-bg-color = "bg-surface"

[modules.media]
icon-color = "green"
icon-bg-color = "transparent"
label-color = "fg-muted"
button-bg-color = "bg-surface"

[modules.media.player-icons]

[modules.microphone]
icon-color = "accent"
icon-bg-color = "accent"
label-color = "accent"
button-bg-color = "transparent"

[modules.network]
button-bg-color = "bg-surface"

[modules.netstat]
label-color = "accent"
button-bg-color = "bg-surface"

[modules.notifications]
border-color = "bg-base"
icon-color = "fg-muted"
icon-bg-color = "transparent"
label-color = "fg-muted"
button-bg-color = "bg-surface"

[modules.ram]
icon-color = "fg-muted"
label-color = "accent"
button-bg-color = "bg-surface"

[modules.systray]
button-bg-color = "bg-surface"

[modules.volume]
icon-color = "accent"
icon-bg-color = "accent"
label-color = "accent"
button-bg-color = "transparent"

[modules.weather]
location = "Kolkata"

[wallpaper]
engine-enabled = false
