[general]
font-sans = "JetBrains Mono Nerd Font"

[bar]
rounding = "md"
button-bg-opacity = 70
button-icon-size = 0.75
button-label-size = 1.0
button-label-weight = "bold"
button-group-background = "bg-surface"
button-group-opacity = 70

[[bar.layout]]
monitor = "*"
show = true
left = [
    "hyprland-workspaces",
    "media",
    "cava",
]
center = [
    "clock",
    "notifications",
]
right = [
    "netstat",
    "ram",
    { name = "audio", modules = [
    "volume",
    "microphone",
] },
    "systray",
    "dashboard",
]

[styling]
scale = 1.0

[styling.palette]
bg = "#11111b"
surface = "#13262e"
elevated = "#13262e"
fg-muted = "#babbf1"
primary = "#babbf1"
red = "#babbf1"
yellow = "#babbf1"
green = "#babbf1"
blue = "#babbf1"

[modules.cava]
bars = 40
color = "#babbf1"
button-bg-color = "bg-surface"
bar-width = 2

[modules.clock]
label-color = "fg-default"
button-bg-color = "bg-surface"

[modules.hyprland-workspaces]
icon-size = 0.75
label-size = 0.75
active-indicator = "underline"
active-color = "fg-default"
occupied-color = "fg-default"
container-bg-color = "bg-surface"

[modules.media]
button-bg-color = "bg-surface"

[modules.microphone]
button-bg-color = "transparent"

[modules.netstat]
button-bg-color = "bg-surface"

[modules.notification]
button-bg-color = "bg-surface"

[modules.ram]
button-bg-color = "bg-surface"

[modules.systray]
button-bg-color = "bg-surface"

[modules.volume]
button-bg-color = "transparent"

[modules.weather]
location = "Kolkata"

[wallpaper]
engine-enabled = false
